version: 'latest'

services:
  nestapp:
    build: ./
    ports:
      - "3000:3001"
    env_file:
      - .env.development
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development

volumes:
  pgdata: