import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/index.css";
import Navbar from "@/components/navbar/Navbar";
import Chat from "@/components/Chat";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GarageJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`${inter.className} bg-cover`}
          style={{ backgroundImage: "url(/fondo2.png)" }}
        >
          <Navbar />
          {children}
          <Chat />
          <Footer />
        </body>
      </html>
    </AuthProvider>
  );
}
